### ISSUE TITLE
Allow to invalidate cache when dependencies changed

### ISSUE THREAD

**Issue by petrnymsa** [jyotirmoy-paul/cached_build_runner#20] opened 2024-01-19 13:52 UTC
If any package, which generates code,  is updated, build_runner does not recognize that and will use cached version. 

This can lead to error where updated dependency assumes different generated code etc. 
---

Runner should cache snapshots of pubspec.lock and allow pruning cache directory if dependencies are updated.

**Comment by tenhobi** [comment] 2024-01-19 14:11
Duplicate of #14

**Closed as completed by tenhobi** 2024-01-19 14:11 UTC
Labels: enhancement
